

<!DOCTYPE html>
<html class="writer-html5" lang="en" data-content_root="../../">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>a_sync.exceptions &mdash; ez-a-sync  documentation</title>
      <link rel="stylesheet" type="text/css" href="../../_static/pygments.css?v=b86133f3" />
      <link rel="stylesheet" type="text/css" href="../../_static/css/theme.css?v=e59714d7" />

  
      <script src="../../_static/jquery.js?v=5d32c60e"></script>
      <script src="../../_static/_sphinx_javascript_frameworks_compat.js?v=2cd50e6c"></script>
      <script src="../../_static/documentation_options.js?v=5929fcd5"></script>
      <script src="../../_static/doctools.js?v=9bcbadda"></script>
      <script src="../../_static/sphinx_highlight.js?v=dc90522c"></script>
    <script src="../../_static/js/theme.js"></script>
    <link rel="index" title="Index" href="../../genindex.html" />
    <link rel="search" title="Search" href="../../search.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >

          
          
          <a href="../../index.html" class="icon icon-home">
            ez-a-sync
          </a>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" aria-label="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <p class="caption" role="heading"><span class="caption-text">Contents:</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../../source/modules.html">a_sync</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../../index.html">ez-a-sync</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="../../index.html" class="icon icon-home" aria-label="Home"></a></li>
          <li class="breadcrumb-item"><a href="../index.html">Module code</a></li>
      <li class="breadcrumb-item active">a_sync.exceptions</li>
      <li class="wy-breadcrumbs-aside">
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <h1>Source code for a_sync.exceptions</h1><div class="highlight"><pre>
<span></span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">This module defines custom exceptions for the a_sync library.</span>
<span class="sd">&quot;&quot;&quot;</span>

<span class="kn">from</span><span class="w"> </span><span class="nn">asyncio</span><span class="w"> </span><span class="kn">import</span> <span class="n">Task</span>

<span class="kn">from</span><span class="w"> </span><span class="nn">a_sync._typing</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>
<span class="kn">from</span><span class="w"> </span><span class="nn">a_sync.a_sync.flags</span><span class="w"> </span><span class="kn">import</span> <span class="n">VIABLE_FLAGS</span>

<span class="k">if</span> <span class="n">TYPE_CHECKING</span><span class="p">:</span>
    <span class="kn">from</span><span class="w"> </span><span class="nn">a_sync</span><span class="w"> </span><span class="kn">import</span> <span class="n">TaskMapping</span>


<div class="viewcode-block" id="ASyncFlagException">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.ASyncFlagException">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">ASyncFlagException</span><span class="p">(</span><span class="ne">ValueError</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Base exception class for flag-related errors in the a_sync library.</span>

<span class="sd">    A-Sync uses &#39;flags&#39; to indicate whether objects or function calls will be sync or async.</span>
<span class="sd">    You can use any of the provided flags, which include &#39;sync&#39; and &#39;asynchronous&#39;, whichever makes most sense for your use case.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise ASyncFlagException(&quot;An error occurred with flags.&quot;)</span>
<span class="sd">        ... except ASyncFlagException as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        An error occurred with flags.</span>

<span class="sd">    See Also:</span>
<span class="sd">        - :const:`VIABLE_FLAGS`</span>
<span class="sd">    &quot;&quot;&quot;</span>

    <span class="n">viable_flags</span> <span class="o">=</span> <span class="n">VIABLE_FLAGS</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;The set of viable flags: {&#39;sync&#39;, &#39;asynchronous&#39;}.&quot;&quot;&quot;</span>

<div class="viewcode-block" id="ASyncFlagException.desc">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.ASyncFlagException.desc">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="nf">desc</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">target</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="nb">str</span><span class="p">:</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Returns a description of the target for the flag error message.</span>

<span class="sd">        Args:</span>
<span class="sd">            target: The target object or string to describe.</span>

<span class="sd">        Examples:</span>
<span class="sd">            &gt;&gt;&gt; exception = ASyncFlagException()</span>
<span class="sd">            &gt;&gt;&gt; exception.desc(&quot;kwargs&quot;)</span>
<span class="sd">            &quot;flags present in &#39;kwargs&#39;&quot;</span>

<span class="sd">            &gt;&gt;&gt; exception.desc(&quot;some_target&quot;)</span>
<span class="sd">            &#39;flag attributes defined on some_target&#39;</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">if</span> <span class="n">target</span> <span class="o">==</span> <span class="s2">&quot;kwargs&quot;</span><span class="p">:</span>
            <span class="k">return</span> <span class="s2">&quot;flags present in &#39;kwargs&#39;&quot;</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="k">return</span> <span class="sa">f</span><span class="s2">&quot;flag attributes defined on </span><span class="si">{</span><span class="n">target</span><span class="si">}</span><span class="s2">&quot;</span></div>
</div>



<div class="viewcode-block" id="NoFlagsFound">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.NoFlagsFound">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">NoFlagsFound</span><span class="p">(</span><span class="n">ASyncFlagException</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when no viable flags are found in the target.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise NoFlagsFound(&quot;some_target&quot;)</span>
<span class="sd">        ... except NoFlagsFound as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        There are no viable a_sync flag attributes defined on some_target:</span>
<span class="sd">        Viable flags: {&#39;sync&#39;, &#39;asynchronous&#39;}</span>
<span class="sd">        This is likely an issue with a custom subclass definition.</span>
<span class="sd">    &quot;&quot;&quot;</span>

<div class="viewcode-block" id="NoFlagsFound.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.NoFlagsFound.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">target</span><span class="p">,</span> <span class="n">kwargs_keys</span><span class="o">=</span><span class="kc">None</span><span class="p">):</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the NoFlagsFound exception.</span>

<span class="sd">        Args:</span>
<span class="sd">            target: The target object where flags were expected.</span>
<span class="sd">            kwargs_keys: Optional; keys in the kwargs if applicable.</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">err</span> <span class="o">=</span> <span class="sa">f</span><span class="s2">&quot;There are no viable a_sync </span><span class="si">{</span><span class="bp">self</span><span class="o">.</span><span class="n">desc</span><span class="p">(</span><span class="n">target</span><span class="p">)</span><span class="si">}</span><span class="s2">:&quot;</span>
        <span class="n">err</span> <span class="o">+=</span> <span class="sa">f</span><span class="s2">&quot;</span><span class="se">\n</span><span class="s2">Viable flags: </span><span class="si">{</span><span class="bp">self</span><span class="o">.</span><span class="n">viable_flags</span><span class="si">}</span><span class="s2">&quot;</span>
        <span class="k">if</span> <span class="n">kwargs_keys</span><span class="p">:</span>
            <span class="n">err</span> <span class="o">+=</span> <span class="sa">f</span><span class="s2">&quot;</span><span class="se">\n</span><span class="s2">kwargs keys: </span><span class="si">{</span><span class="n">kwargs_keys</span><span class="si">}</span><span class="s2">&quot;</span>
        <span class="n">err</span> <span class="o">+=</span> <span class="s2">&quot;</span><span class="se">\n</span><span class="s2">This is likely an issue with a custom subclass definition.&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span></div>
</div>



<div class="viewcode-block" id="TooManyFlags">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.TooManyFlags">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">TooManyFlags</span><span class="p">(</span><span class="n">ASyncFlagException</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when multiple flags are found, but only one was expected.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise TooManyFlags(&quot;some_target&quot;, [&quot;flag1&quot;, &quot;flag2&quot;])</span>
<span class="sd">        ... except TooManyFlags as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        There are multiple a_sync flag attributes defined on some_target and there should only be one.</span>
<span class="sd">        Present flags: [&#39;flag1&#39;, &#39;flag2&#39;]</span>
<span class="sd">        This is likely an issue with a custom subclass definition.</span>
<span class="sd">    &quot;&quot;&quot;</span>

<div class="viewcode-block" id="TooManyFlags.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.TooManyFlags.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">target</span><span class="p">,</span> <span class="n">present_flags</span><span class="p">):</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the TooManyFlags exception.</span>

<span class="sd">        Args:</span>
<span class="sd">            target: The target object where flags were found.</span>
<span class="sd">            present_flags: The flags that were found.</span>

<span class="sd">        See Also:</span>
<span class="sd">            - :class:`ASyncFlagException`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">err</span> <span class="o">=</span> <span class="sa">f</span><span class="s2">&quot;There are multiple a_sync </span><span class="si">{</span><span class="bp">self</span><span class="o">.</span><span class="n">desc</span><span class="p">(</span><span class="n">target</span><span class="p">)</span><span class="si">}</span><span class="s2"> and there should only be one.</span><span class="se">\n</span><span class="s2">&quot;</span>
        <span class="n">err</span> <span class="o">+=</span> <span class="sa">f</span><span class="s2">&quot;Present flags: </span><span class="si">{</span><span class="n">present_flags</span><span class="si">}</span><span class="se">\n</span><span class="s2">&quot;</span>
        <span class="n">err</span> <span class="o">+=</span> <span class="s2">&quot;This is likely an issue with a custom subclass definition.&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span></div>
</div>



<div class="viewcode-block" id="InvalidFlag">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.InvalidFlag">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">InvalidFlag</span><span class="p">(</span><span class="n">ASyncFlagException</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when an invalid flag is encountered.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise InvalidFlag(&quot;invalid_flag&quot;)</span>
<span class="sd">        ... except InvalidFlag as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        &#39;flag&#39; must be one of: {&#39;sync&#39;, &#39;asynchronous&#39;}. You passed invalid_flag.</span>
<span class="sd">        This code should not be reached and likely indicates an issue with a custom subclass definition.</span>

<span class="sd">    See Also:</span>
<span class="sd">        - :const:`VIABLE_FLAGS`</span>
<span class="sd">    &quot;&quot;&quot;</span>

<div class="viewcode-block" id="InvalidFlag.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.InvalidFlag.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">flag</span><span class="p">:</span> <span class="n">Optional</span><span class="p">[</span><span class="nb">str</span><span class="p">]):</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the InvalidFlag exception.</span>

<span class="sd">        Args:</span>
<span class="sd">            flag: The invalid flag.</span>

<span class="sd">        See Also:</span>
<span class="sd">            - :class:`ASyncFlagException`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">err</span> <span class="o">=</span> <span class="sa">f</span><span class="s2">&quot;&#39;flag&#39; must be one of: </span><span class="si">{</span><span class="bp">self</span><span class="o">.</span><span class="n">viable_flags</span><span class="si">}</span><span class="s2">. You passed </span><span class="si">{</span><span class="n">flag</span><span class="si">}</span><span class="s2">.&quot;</span>
        <span class="n">err</span> <span class="o">+=</span> <span class="s2">&quot;</span><span class="se">\n</span><span class="s2">This code should not be reached and likely indicates an issue with a custom subclass definition.&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span></div>
</div>



<div class="viewcode-block" id="InvalidFlagValue">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.InvalidFlagValue">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">InvalidFlagValue</span><span class="p">(</span><span class="n">ASyncFlagException</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when a flag has an invalid value.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise InvalidFlagValue(&quot;some_flag&quot;, &quot;not_a_boolean&quot;)</span>
<span class="sd">        ... except InvalidFlagValue as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        &#39;some_flag&#39; should be boolean. You passed not_a_boolean.</span>
<span class="sd">    &quot;&quot;&quot;</span>

<div class="viewcode-block" id="InvalidFlagValue.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.InvalidFlagValue.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">flag</span><span class="p">:</span> <span class="nb">str</span><span class="p">,</span> <span class="n">flag_value</span><span class="p">:</span> <span class="n">Any</span><span class="p">):</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the InvalidFlagValue exception.</span>

<span class="sd">        Args:</span>
<span class="sd">            flag: The flag with an invalid value.</span>
<span class="sd">            flag_value: The invalid value of the flag.</span>

<span class="sd">        See Also:</span>
<span class="sd">            - :class:`ASyncFlagException`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="sa">f</span><span class="s2">&quot;&#39;</span><span class="si">{</span><span class="n">flag</span><span class="si">}</span><span class="s2">&#39; should be boolean. You passed </span><span class="si">{</span><span class="n">flag_value</span><span class="si">}</span><span class="s2">.&quot;</span><span class="p">)</span></div>
</div>



<div class="viewcode-block" id="FlagNotDefined">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.FlagNotDefined">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">FlagNotDefined</span><span class="p">(</span><span class="n">ASyncFlagException</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when a flag is not defined on an object.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; class SomeClass:</span>
<span class="sd">        ...     pass</span>
<span class="sd">        ...</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise FlagNotDefined(SomeClass, &quot;some_flag&quot;)</span>
<span class="sd">        ... except FlagNotDefined as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        &lt;class &#39;__main__.SomeClass&#39;&gt; flag some_flag is not defined.</span>
<span class="sd">    &quot;&quot;&quot;</span>

<div class="viewcode-block" id="FlagNotDefined.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.FlagNotDefined.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">obj</span><span class="p">:</span> <span class="n">Type</span><span class="p">,</span> <span class="n">flag</span><span class="p">:</span> <span class="nb">str</span><span class="p">):</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the FlagNotDefined exception.</span>

<span class="sd">        Args:</span>
<span class="sd">            obj: The object where the flag is not defined.</span>
<span class="sd">            flag: The undefined flag.</span>

<span class="sd">        See Also:</span>
<span class="sd">            - :class:`ASyncFlagException`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="sa">f</span><span class="s2">&quot;</span><span class="si">{</span><span class="n">obj</span><span class="si">}</span><span class="s2"> flag </span><span class="si">{</span><span class="n">flag</span><span class="si">}</span><span class="s2"> is not defined.&quot;</span><span class="p">)</span></div>
</div>



<div class="viewcode-block" id="ImproperFunctionType">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.ImproperFunctionType">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">ImproperFunctionType</span><span class="p">(</span><span class="ne">ValueError</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when a function that should be sync is async or vice-versa.</span>

<span class="sd">    See Also:</span>
<span class="sd">        - :class:`FunctionNotAsync`</span>
<span class="sd">        - :class:`FunctionNotSync`</span>
<span class="sd">    &quot;&quot;&quot;</span></div>



<div class="viewcode-block" id="FunctionNotAsync">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.FunctionNotAsync">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">FunctionNotAsync</span><span class="p">(</span><span class="n">ImproperFunctionType</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when a function expected to be async is not.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; def some_function():</span>
<span class="sd">        ...     pass</span>
<span class="sd">        ...</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise FunctionNotAsync(some_function)</span>
<span class="sd">        ... except FunctionNotAsync as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        `coro_fn` must be a coroutine function defined with `async def`. You passed &lt;function some_function at 0x...&gt;.</span>
<span class="sd">    &quot;&quot;&quot;</span>

<div class="viewcode-block" id="FunctionNotAsync.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.FunctionNotAsync.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">fn</span><span class="p">):</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the FunctionNotAsync exception.</span>

<span class="sd">        Args:</span>
<span class="sd">            fn: The function that is not async.</span>

<span class="sd">        See Also:</span>
<span class="sd">            - :class:`ImproperFunctionType`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span>
            <span class="bp">self</span><span class="p">,</span>
            <span class="sa">f</span><span class="s2">&quot;`coro_fn` must be a coroutine function defined with `async def`. You passed </span><span class="si">{</span><span class="n">fn</span><span class="si">}</span><span class="s2">.&quot;</span><span class="p">,</span>
        <span class="p">)</span></div>
</div>



<div class="viewcode-block" id="FunctionNotSync">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.FunctionNotSync">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">FunctionNotSync</span><span class="p">(</span><span class="n">ImproperFunctionType</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when a function expected to be sync is actually async.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; async def some_async_function():</span>
<span class="sd">        ...     pass</span>
<span class="sd">        ...</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise FunctionNotSync(some_async_function)</span>
<span class="sd">        ... except FunctionNotSync as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        `func` must be a coroutine function defined with `def`. You passed &lt;function some_async_function at 0x...&gt;.</span>
<span class="sd">    &quot;&quot;&quot;</span>

<div class="viewcode-block" id="FunctionNotSync.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.FunctionNotSync.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">fn</span><span class="p">):</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the FunctionNotSync exception.</span>

<span class="sd">        Args:</span>
<span class="sd">            fn: The function that is not sync.</span>

<span class="sd">        See Also:</span>
<span class="sd">            - :class:`ImproperFunctionType`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span>
            <span class="bp">self</span><span class="p">,</span> <span class="sa">f</span><span class="s2">&quot;`func` must be a coroutine function defined with `def`. You passed </span><span class="si">{</span><span class="n">fn</span><span class="si">}</span><span class="s2">.&quot;</span>
        <span class="p">)</span></div>
</div>



<div class="viewcode-block" id="ASyncRuntimeError">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.ASyncRuntimeError">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">ASyncRuntimeError</span><span class="p">(</span><span class="ne">RuntimeError</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised for runtime errors in asynchronous operations.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise ASyncRuntimeError(RuntimeError(&quot;Some runtime error&quot;))</span>
<span class="sd">        ... except ASyncRuntimeError as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        Some runtime error</span>
<span class="sd">    &quot;&quot;&quot;</span>

<div class="viewcode-block" id="ASyncRuntimeError.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.ASyncRuntimeError.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">e</span><span class="p">:</span> <span class="ne">RuntimeError</span><span class="p">):</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the ASyncRuntimeError exception.</span>

<span class="sd">        Args:</span>
<span class="sd">            e: The original runtime error.</span>

<span class="sd">        See Also:</span>
<span class="sd">            - :class:`RuntimeError`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="nb">str</span><span class="p">(</span><span class="n">e</span><span class="p">))</span></div>
</div>



<div class="viewcode-block" id="SyncModeInAsyncContextError">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.SyncModeInAsyncContextError">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">SyncModeInAsyncContextError</span><span class="p">(</span><span class="n">ASyncRuntimeError</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when synchronous code is used within an asynchronous context.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise SyncModeInAsyncContextError()</span>
<span class="sd">        ... except SyncModeInAsyncContextError as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        The event loop is already running, which means you&#39;re trying to use an `ASyncFunction` synchronously from within an async context.</span>
<span class="sd">        Check your traceback to determine which, then try calling asynchronously instead with one of the following kwargs:</span>
<span class="sd">        {&#39;sync&#39;, &#39;asynchronous&#39;}</span>
<span class="sd">    &quot;&quot;&quot;</span>

<div class="viewcode-block" id="SyncModeInAsyncContextError.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.SyncModeInAsyncContextError.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span> <span class="nb">str</span> <span class="o">=</span> <span class="s2">&quot;&quot;</span><span class="p">):</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the SyncModeInAsyncContextError exception.</span>

<span class="sd">        See Also:</span>
<span class="sd">            - :class:`ASyncRuntimeError`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="n">err</span><span class="p">:</span>
            <span class="n">err</span> <span class="o">=</span> <span class="s2">&quot;The event loop is already running, which means you&#39;re trying to use an `ASyncFunction` synchronously from within an async context.</span><span class="se">\n</span><span class="s2">&quot;</span>
            <span class="n">err</span> <span class="o">+=</span> <span class="sa">f</span><span class="s2">&quot;Check your traceback to determine which, then try calling asynchronously instead with one of the following kwargs:</span><span class="se">\n</span><span class="s2">&quot;</span>
            <span class="n">err</span> <span class="o">+=</span> <span class="sa">f</span><span class="s2">&quot;</span><span class="si">{</span><span class="n">VIABLE_FLAGS</span><span class="si">}</span><span class="s2">&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span></div>
</div>



<div class="viewcode-block" id="MappingError">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.MappingError">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">MappingError</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Base class for errors related to :class:`~TaskMapping`.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; from a_sync import TaskMapping</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise MappingError(TaskMapping(), &quot;Some mapping error&quot;)</span>
<span class="sd">        ... except MappingError as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        Some mapping error:</span>
<span class="sd">        &lt;TaskMapping object at 0x...&gt;</span>
<span class="sd">        {}</span>
<span class="sd">    &quot;&quot;&quot;</span>

    <span class="n">_msg</span><span class="p">:</span> <span class="nb">str</span>

<div class="viewcode-block" id="MappingError.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.MappingError.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">mapping</span><span class="p">:</span> <span class="s2">&quot;TaskMapping&quot;</span><span class="p">,</span> <span class="n">msg</span><span class="p">:</span> <span class="nb">str</span> <span class="o">=</span> <span class="s2">&quot;&quot;</span><span class="p">):</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the MappingError exception.</span>

<span class="sd">        Args:</span>
<span class="sd">            mapping: The TaskMapping where the error occurred.</span>
<span class="sd">            msg: An optional message describing the error.</span>

<span class="sd">        See Also:</span>
<span class="sd">            - :class:`TaskMapping`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">msg</span> <span class="o">=</span> <span class="p">(</span><span class="n">msg</span> <span class="ow">or</span> <span class="bp">self</span><span class="o">.</span><span class="n">_msg</span><span class="p">)</span> <span class="o">+</span> <span class="sa">f</span><span class="s2">&quot;:</span><span class="se">\n</span><span class="si">{</span><span class="n">mapping</span><span class="si">}</span><span class="s2">&quot;</span>
        <span class="k">if</span> <span class="n">mapping</span><span class="p">:</span>
            <span class="n">msg</span> <span class="o">+=</span> <span class="sa">f</span><span class="s2">&quot;</span><span class="se">\n</span><span class="si">{</span><span class="nb">dict</span><span class="p">(</span><span class="n">mapping</span><span class="p">)</span><span class="si">}</span><span class="s2">&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">msg</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">mapping</span> <span class="o">=</span> <span class="n">mapping</span></div>
</div>



<div class="viewcode-block" id="MappingIsEmptyError">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.MappingIsEmptyError">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">MappingIsEmptyError</span><span class="p">(</span><span class="n">MappingError</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when a TaskMapping is empty and an operation requires it to have items.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; from a_sync import TaskMapping</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise MappingIsEmptyError(TaskMapping())</span>
<span class="sd">        ... except MappingIsEmptyError as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        TaskMapping does not contain anything to yield:</span>
<span class="sd">        &lt;TaskMapping object at 0x...&gt;</span>
<span class="sd">        {}</span>
<span class="sd">    &quot;&quot;&quot;</span>

    <span class="n">_msg</span> <span class="o">=</span> <span class="s2">&quot;TaskMapping does not contain anything to yield&quot;</span></div>



<div class="viewcode-block" id="MappingNotEmptyError">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.MappingNotEmptyError">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">MappingNotEmptyError</span><span class="p">(</span><span class="n">MappingError</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when a TaskMapping is not empty and an operation requires it to be empty.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; from a_sync import TaskMapping</span>
<span class="sd">        &gt;&gt;&gt; task_mapping = TaskMapping()</span>
<span class="sd">        &gt;&gt;&gt; task_mapping[&#39;key&#39;] = &#39;value&#39;</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise MappingNotEmptyError(task_mapping)</span>
<span class="sd">        ... except MappingNotEmptyError as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        TaskMapping already contains some data. In order to use `map`, you need a fresh one:</span>
<span class="sd">        &lt;TaskMapping object at 0x...&gt;</span>
<span class="sd">        {&#39;key&#39;: &#39;value&#39;}</span>
<span class="sd">    &quot;&quot;&quot;</span>

    <span class="n">_msg</span> <span class="o">=</span> <span class="s2">&quot;TaskMapping already contains some data. In order to use `map`, you need a fresh one&quot;</span></div>



<div class="viewcode-block" id="PersistedTaskException">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.PersistedTaskException">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">PersistedTaskException</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when an exception persists in an asyncio Task.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; import asyncio</span>
<span class="sd">        &gt;&gt;&gt; async def some_task():</span>
<span class="sd">        ...     raise ValueError(&quot;Some error&quot;)</span>
<span class="sd">        ...</span>
<span class="sd">        &gt;&gt;&gt; task = asyncio.create_task(some_task())</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise PersistedTaskException(ValueError(&quot;Some error&quot;), task)</span>
<span class="sd">        ... except PersistedTaskException as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        ValueError: Some error</span>
<span class="sd">    &quot;&quot;&quot;</span>

<div class="viewcode-block" id="PersistedTaskException.__init__">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.PersistedTaskException.__init__">[docs]</a>
    <span class="k">def</span><span class="w"> </span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">exc</span><span class="p">:</span> <span class="n">E</span><span class="p">,</span> <span class="n">task</span><span class="p">:</span> <span class="n">Task</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="kc">None</span><span class="p">:</span>
<span class="w">        </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        Initializes the PersistedTaskException exception.</span>

<span class="sd">        Args:</span>
<span class="sd">            exc: The exception that persisted.</span>
<span class="sd">            task: The asyncio Task where the exception occurred.</span>

<span class="sd">        See Also:</span>
<span class="sd">            - :class:`asyncio.Task`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="ne">BaseException</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="sa">f</span><span class="s2">&quot;</span><span class="si">{</span><span class="n">exc</span><span class="o">.</span><span class="vm">__class__</span><span class="o">.</span><span class="vm">__name__</span><span class="si">}</span><span class="s2">: </span><span class="si">{</span><span class="n">exc</span><span class="si">}</span><span class="s2">&quot;</span><span class="p">,</span> <span class="n">task</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">exception</span> <span class="o">=</span> <span class="n">exc</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">task</span> <span class="o">=</span> <span class="n">task</span></div>
</div>



<div class="viewcode-block" id="EmptySequenceError">
<a class="viewcode-back" href="../../source/a_sync.html#a_sync.exceptions.EmptySequenceError">[docs]</a>
<span class="k">class</span><span class="w"> </span><span class="nc">EmptySequenceError</span><span class="p">(</span><span class="ne">ValueError</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    Raised when an operation is attempted on an empty sequence but items are required.</span>

<span class="sd">    Examples:</span>
<span class="sd">        &gt;&gt;&gt; try:</span>
<span class="sd">        ...     raise EmptySequenceError(&quot;Sequence is empty&quot;)</span>
<span class="sd">        ... except EmptySequenceError as e:</span>
<span class="sd">        ...     print(e)</span>
<span class="sd">        Sequence is empty</span>
<span class="sd">    &quot;&quot;&quot;</span></div>

</pre></div>

           </div>
          </div>
          <footer>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2024, BobTheBuidler.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>